COMPILE_DEPS = CORE_DEPS + [
    "//apps/grpc-integration/protobuf/models/proto:onos-apps-grpc-integration-protobuf-models-proto",
    #"//core/protobuf/models/proto:onos-core-protobuf-models-proto",
    #"//core/protobuf/models/proto:onos-core-protobuf-services-proto",
    "@com_google_protobuf//:protobuf_java",
]

osgi_jar_with_tests(
    deps = COMPILE_DEPS,
)
